#
# JBZoo Toolbox - Mock-Server
#
# This file is part of the JBZoo Toolbox project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @package    Mock-Server
# @license    MIT
# @copyright  Copyright (C) JBZoo.com, All rights reserved.
# @link       https://github.com/JBZoo/Mock-Server
#

language: php
os: linux
dist: xenial

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - nightly

jobs:
  fast_finish: true
  allow_failures:
    - php: 8.0
    - php: nightly

before_script:
  - composer self-update

script:
  - make build    --no-print-directory
  - make test-all --no-print-directory


after_script:
  - cat ./build/server.log
  - make report-coveralls


deploy:
  provider: releases
  token:
    secure: d7hazE8qinWxCZ9tjcTGGu8Xr/hAaSNzOKvsr0j9GVbYDjD0DS+q16jmRWOJHDKEW6WpCh81+Uhp3UspsaMyntI7/Rp0PBKAzYBlMvsqKS/ZiSBuHy2z+AzkK7OOa8wOG2O0M54ytfJLGYKOizdw+yPFiom/1Cyd9z2ER4d7Po/ZNwHxCoyg8ug9zgzP5T52u31kyBEGVeRBfMLdWw1/DQsR5Jw6Zv9Bgr1i/Z9nLhxUosFPKldlnGM5pZfQmBff/k7xSZKuh+FgP7KBZcco+QZ5zqlGN6JPWjkOLjqP0qCSjcsrtDg3c3wu2PKbKziEbGuyjrMbGjatK02ayg3HXur07Lq2QJskTTRtRQ8t1QvGXB73hvzS8NPa93MHy4Mjotzg1NqVcDGoBK6arUMbGgXhN75W4g9GygTHGjBKx7DUcYBPsayqjtlWEMhAcXTclVopGtcH5+jXOyQ0zzm+4bB3wVhVHXiaQmkhosz26wrgBkmpZnvYm1m/Lh1GyCPYfjtCxRifkAsFSj50JuLzcLnwsBP5sax2JSnfFjnSlbROJA0CbDkpGK2GghXCrurHGD1EVkFBfoGF/vJ95x7vt9LfEXNhYxMQ2qzRjV0WBs0i3lAbpzP8Wu0rPY0WzOcjEU/YK+OLpSyuX2eiDfX/0fJWBircBMShnkXJxyOU3nU=
  file: "./build/mock-server.phar"
  on:
    tags: true
  overwrite: true
  skip_cleanup: true
