#
# JBZoo Toolbox - Mock-Server
#
# This file is part of the JBZoo Toolbox project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @package    Mock-Server
# @license    MIT
# @copyright  Copyright (C) JBZoo.com, All rights reserved.
# @link       https://github.com/JBZoo/Mock-Server
#

language: php
os: linux
dist: xenial

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 8.0
    - php: nightly

before_script:
  - composer self-update

script:
  - make update     --no-print-directory
  - make build-phar --no-print-directory
  - make up-phar-bg --no-print-directory
  - make test       --no-print-directory
  - make down up-bg --no-print-directory
  - make test       --no-print-directory
  - make codestyle     --no-print-directory

after_script:
  - cat ./build/server.log
  - make report-coveralls
